### ISSUE TITLE
Which evaluation mode should I use?

### ISSUE THREAD

**Issue by Yeom** [Franck-Dernoncourt/NeuroNER#1]
I want to train toy dataset. This dataset is not NamedEntity Recognition dataset but it's labeld by BIO format
For example) B-TIME, B-DATE, B-EVENT ... Like this.

what should i use evaluation mode? BIO? or Token?

**Comment by Franck-Dernoncourt** [comment]
Both evaluation modes should work.

**Comment by Yeom** [comment]
Thank you so much :)!!
