### ISSUE TITLE
Please add License version

### ISSUE THREAD

**Issue by purohitvivek8** [Franck-Dernoncourt/NeuroNER#111]
Hello @Franck-Dernoncourt @toliwa @JohnGiorgi @jennyjylee @Gregory-Howard 
Please add license

**Comment by tompollard** [comment]
Duplicate of https://github.com/Franck-Dernoncourt/NeuroNER/issues/89, https://github.com/Franck-Dernoncourt/NeuroNER/issues/46, https://github.com/Franck-Dernoncourt/NeuroNER/issues/15
