### ISSUE TITLE
I want to get i2b2 2014 dataset

### ISSUE THREAD

**Issue by neverneverendup** [Franck-Dernoncourt/NeuroNER#124]
I send an email to the orgnization : schurchill@partners.org,but there is no reply...Could you give me the i2b2 2014 dataset?I just want to train my model.Thanks！

**Comment by tompollard** [comment]
We do not have permission to share the dataset. You will need to request it in the standard way, by following the instructions at: https://www.i2b2.org/NLP/DataSets/Main.php

> To access these notes, please use the Registration link to your left.  We will do an expedited review of your proposal and, if acceptable, will ask you to sign and return our standard Data Use Agreement before releasing the notes to you.  Given the goal of leveraging the entire community, we will ask that you share your annotations back to us following publication of your results and/or one year after first access, whichever comes first.
