### ISSUE TITLE
Make package pip installable

### ISSUE THREAD

**Issue by tompollard** [Franck-Dernoncourt/NeuroNER#133]
I'd like to support application of pre-trained NeuroNER models in a deidentification package that we are working on. It would be easier to do this if NeuroNER was made pip installable. Steps to make pip installable: https://packaging.python.org/tutorials/packaging-projects/

**Comment by tompollard** [comment]
The package will need a new name for distribution on PyPi because "neuroner" is taken: https://pypi.org/project/neuroner/. How about "pyneuroner" or "neuronerpy"? Any better suggestions?

**Comment by Franck-Dernoncourt** [comment]
Thanks, pyneuroner sounds good!

**Comment by tompollard** [comment]
Now available on Pypi at: https://pypi.org/project/pyneuroner/

Installable with `pip install pyneuroner`
