### ISSUE TITLE
Character embedding question

### ISSUE THREAD

**Issue by ntzky** [Franck-Dernoncourt/NeuroNER#135]
How did you represent a character as a vector? I found the file "tensorboard_metadata_characters.tsv", did you use 1-hot encoding?

**Comment by Franck-Dernoncourt** [comment]
We used character embeddings (default dimension: 25). You can change the dimension in `parameters.ini` by changing the value of`character_embedding_dimension`.

See https://doi.org/10.1093/jamia/ocw156 for the model description.
