### ISSUE TITLE
The output file is not created. 

### ISSUE THREAD

**Issue by elsaresearch** [Franck-Dernoncourt/NeuroNER#14]
Hi.. First of all, I will explain the steps what I have done for unannotated texts.

The dataset folder now contains a deploy folder with phrase.txt. No other files are included. In that case, when I run, main.py, I am getting the error as train.txt is not found. (FileNotFoundError).

If I include train,test and valid files in the same folder, it's running, but I am not getting the expected output.

As per the instructions given, I have changed these parameters in src ini file:
train_model=False
use_pretrained_model=True
pretrained_model_folder=../trained_models/conll_2003_en
dataset_text_folder=../data/dataset

use_character_lstm=True
character_embedding_dimension=25
character_lstm_hidden_state_dimension=25
token_pretrained_embedding_filepath=../data/word_vectors/glove.6B.100d.txt
token_embedding_dimension=100
token_lstm_hidden_state_dimension=100

use_crf=True
tagging_format=bioes
tokenizer=spacy

Please help me to find out what error I am making in this.

**Comment by Franck-Dernoncourt** [comment]
I'm surprised you get `train.txt is not found. (FileNotFoundError)` despite setting `train_model=False`. I currently don't see what could cause it.

Have you tried running the example showing how to perform NER on some plain texts using a pre-trained model in the [readme](https://github.com/Franck-Dernoncourt/NeuroNER#using-neuroner)? I.e., running the following command (assuming the [`src/parameters.ini`](src/https://github.com/Franck-Dernoncourt/NeuroNER/blob/master/src/parameters.ini) configuration file is the same as the one on GitHub):


> ```
> python3.5 main.py --train_model=False --use_pretrained_model=True --dataset_text_folder=../data/example_unannotated_texts --pretrained_model_folder=../trained_models/conll_2003_en
> ```

**Comment by nancyvictor** [comment]
I have tried that and it's showing a new error as follows:
 line 291, in load_dataset
    self.alphabet_size = max(self.index_to_character.keys()) + 1

ValueError: max( ) arg is an empty sequence

**Comment by elsaresearch** [comment]
I have tried that and it's showing a new error as follows:
line 291, in load_dataset
self.alphabet_size = max(self.index_to_character.keys()) + 1
ValueError: max( ) arg is an empty sequence

**Comment by Franck-Dernoncourt** [comment]
I think this means that for some reason `/data/example_unannotated_texts/deploy_spacy.txt` is empty. Could you please re-clone the repository and try again


> ```
> python3.5 main.py --train_model=False --use_pretrained_model=True --dataset_text_folder=../data/example_unannotated_texts --pretrained_model_folder=../trained_models/conll_2003_en
> ```

?

**Comment by Aparna-B** [comment]
Hi,
I am getting the same error as @elsaresearch above on trying out a pre-trained model.
And am unable to find the 'deploy_spacy.txt' and 'deploy_spacy_bioes.txt' on cloning the repository or in the repository here.

**Comment by Franck-Dernoncourt** [comment]
Did it solve your issue?

**Comment by elsaresearch** [comment]
Hi... I am not getting the output for unannotated texts. I hope the issue is with the Spacy installation. I tried all the three ways you have mentioned for Spacy installation. But, none of the methods work fine for me. I have tried with virtual environment also. Even tried with Spacy website documentation. 

I am trying day and night for that Spacy :'(

**Comment by Franck-Dernoncourt** [comment]
Do you still have the same error message?

**Comment by Franck-Dernoncourt** [comment]
Somebody else had the same issue as you. Please look at https://github.com/Franck-Dernoncourt/NeuroNER/issues/18#issuecomment-307578225 and let me know if it solves your issue.

**Comment by elsaresearch** [comment]
Hi ... 

Thank you so much. The issue was with the installation of Spacy. I have tried a system installation (C:\Windows\system32) for Spacy and it's working fine now. :)

**Comment by Franck-Dernoncourt** [comment]
Glad to hear, thanks for the feedback! How did you install it system-wide?

**Comment by elsaresearch** [comment]
Actually I was getting the error as "OSError: Symbolic link privilege not held", when trying to install Spacy. Solved the issue by going for a system wide installation as follows:

  1.  Go to Start->All Programs-> Accessories-> Right click on Command Prompt and select "Run as administrator".

   2. Once the command prompt is opened, pip install or conda install spacy. 

And, thank you once again for this NeuroNER. Actually, I am working on unstructured data analysis and this helps me a lot. :)
