### ISSUE TITLE
Installation issue on macos

### ISSUE THREAD

**Issue by desmondhw** [Franck-Dernoncourt/NeuroNER#142]
Hi when I do pip3 install pyneuroner[cpu] in bash on my mac I run into this problem.

gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/private/var/folders/sm/jnmn9w1d6nz7kq544472rpdr0000gn/T/pip-install-xdteo6lj/spacy/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c spacy/_align.cpp -o build/temp.macosx-10.9-x86_64-3.7/spacy/_align.o -O2 -Wno-strict-prototypes -Wno-unused-function -stdlib=libc++
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/sm/jnmn9w1d6nz7kq544472rpdr0000gn/T/pip-install-xdteo6lj/spacy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/sm/jnmn9w1d6nz7kq544472rpdr0000gn/T/pip-record-4y1_k53b/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/sm/jnmn9w1d6nz7kq544472rpdr0000gn/T/pip-install-xdteo6lj/spacy/

How can I solve this?

**Comment by tompollard** [comment]
Try installing the osx command line tools by following the suggestions at : https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by tompollard** [comment]
@desmondhw I'm assuming this issue was resolved. Please reopen if not!
