### ISSUE TITLE
AttributeError: 'NeuroNER' object has no attribute 'sess'

### ISSUE THREAD

**Issue by Mahmedturk** [Franck-Dernoncourt/NeuroNER#143]
Hi,

I get the the following error with conll dataset. I know this has already been answered but that fix does not solve my issue. 

__AttributeError: 'NeuroNER' object has no attribute 'sess'

**Comment by Franck-Dernoncourt** [comment]
Thanks for the report, duplicate of #87 (see the [last comment](https://github.com/Franck-Dernoncourt/NeuroNER/issues/87#issuecomment-480507542) -> the issue is due to a recent update, will be fixed soon)

**Comment by nishkalavallabhi** [comment]
I just installed neuroner, and I have this exact same error (not with conll, but with a different dataset in bio, which works with other trainers). Is there a fix?

**Comment by garimazthakur** [comment]
Please check your spacy module once.
