### ISSUE TITLE
Evaluation metric?

### ISSUE THREAD

**Issue by Mahmedturk** [Franck-Dernoncourt/NeuroNER#144]
Hi,

Does this implementation report token-level or entity level F1 score?

**Comment by Franck-Dernoncourt** [comment]
It reports both. You can choose with the option [`main_evaluation_mode`](https://github.com/Franck-Dernoncourt/NeuroNER/blob/18f730e10c9a35464ee2927b56cf19d6fd0dc966/parameters.ini#L22-L24) in `parameters.ini`.
