### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fnl** [Franck-Dernoncourt/NeuroNER#15]
As you provide no explicit license, that makes this project unusable to anybody. No license is equivalent to "[only look, don't touch](https://stackoverflow.com/questions/5521080/can-i-use-the-code-in-a-github-project-which-does-not-have-a-license-specified)". Even in a purely academic or research context, it is technically illegal to use code from a repo with no license.

**Comment by hate5six** [comment]
Agreed. A license would be greatly appreciated. Thanks!

**Comment by kleag** [comment]
Exact. No license, no reuse...

**Comment by albertotonon** [comment]
I noticed that a part is using some functionalities coming from Stanford CoreNLP, so, I guess the licensing of that part would be GPL v2?

**Comment by vineetk1** [comment]
Please provide a response to the question of License that is being raised by many people?

**Comment by autuus** [comment]
How about [WTFPL](https://en.wikipedia.org/wiki/WTFPL)

**Comment by jimmy-fan** [comment]
Hi @Franck-Dernoncourt, is there a license to allow reusing the code in this repo?  Much thanks.

**Comment by pchc2005** [comment]
hi @Franck-Dernoncourt , I would like to ask for a license to use your code in my project. Many thanks! :)

**Comment by pombredanne** [comment]
There is a MIT license referenced there https://github.com/Franck-Dernoncourt/NeuroNER/blob/9347dbc63dd2cefc8f9e117cb154e60f87bb0aa3/setup.py#L37 but this may not be the author's intent. Short of anything else, that's the only license information.

@jennyjylee and @tompollard since you are major contributors, what is the license of your code, since @Franck-Dernoncourt does not seem to be willing to provide some indication.

**Comment by tompollard** [comment]
@pombredanne I'm happy for my contributions to be MIT licensed, but I'd like to check with Franck and Jenny too. I don't think unwillingness is the issue - they are just busy peeps and have other priorities right now. I'll follow up with them and hope to clarify the license within a week.

**Comment by pombredanne** [comment]
@tompollard re:

>  I don't think unwillingness is the issue - they are just busy peeps and have other priorities right now. I'll follow up with them and hope to clarify the license within a week.

Thank you very much!

**Comment by pombredanne** [comment]
@Franck-Dernoncourt Thank you for following up :bowing_man:

**Comment by Franck-Dernoncourt** [comment]
@pombredanne you're welcome, sorry for the delay!

**Comment by fnl** [comment]
As others pointed out, other dependencies have much less favorable licenses, but now the code at least becomes reusable. Thank you very much, @Franck-Dernoncourt and @tompollard, for resolving this long-standing ticket!
