### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by obai-d** [Franck-Dernoncourt/NeuroNER#154]
Running `neuroner --fetch_data=conll2003` gives me the following error.
```
Traceback (most recent call last):
  File "pyneuroner/bin/neuroner", line 5, in <module>
    from neuroner.__main__ import main
  File "pyneuroner/lib/python3.7/site-packages/neuroner/__main__.py", line 16, in <module>
    from neuroner import neuromodel
  File "pyneuroner/lib/python3.7/site-packages/neuroner/neuromodel.py", line 20, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

Apparently in TF2 'tensorflow.contrib' isn't there? Or is it a problem on my side?

**Comment by Franck-Dernoncourt** [comment]
Correct, `tensorflow.contrib` isn't in TensorFlow 2.x. 

From https://www.tensorflow.org/guide/upgrade ([mirror](https://web.archive.org/web/20191102221141/https://www.tensorflow.org/guide/upgrade)):

> Because of TensorFlow 2.x module deprecations (for example, tf.flags and tf.contrib ), some changes can not be worked around by switching to compat.v1 .

Try using `tensorflow==1.1.0`

**Comment by obai-d** [comment]
Thanks, will try that.
