### ISSUE TITLE
xml data format instead of plain text file during train, test & validation 

### ISSUE THREAD

**Issue by ashikrafi** [Franck-Dernoncourt/NeuroNER#161]
Dear Team,

Thank you very much for NeuroNER. You guys have done some tremendous work. Thank you.

However, I have been working on NeuroNER. Instead of plain text file, I have got xml data source for training, testing and validation.Can you please me how to use xml data?

Thank you

**Comment by kaushikacharya** [comment]
@ashikrafi 
You would need to parse the xml data and dump into text file in the format as mentioned in https://github.com/Franck-Dernoncourt/NeuroNER#adding-a-new-dataset

For parsing the xml, you can follow the instructions mentioned here: https://docs.python.org/3.7/library/xml.etree.elementtree.html#parsing-xml

**Comment by ashikrafi** [comment]
@kaushikacharya 
Thank you. It helped me a lot.
