### ISSUE TITLE
NeuroNER installation on Windows

### ISSUE THREAD

**Issue by Rabia-Noureen** [Franck-Dernoncourt/NeuroNER#20]
I am new to python and have been trying to install and run NeuroNER  on windows  for 2 days but its not running and i think i am not able to install it properly on windows 10 54 bit OS. The installation tutorial for Ubuntu is available but for windows i am unable to find any video tutorial. Can any one please create a step by step video tutorial or installation manual with step by step snapshots?  I really need it for my MS research ASAP.

**Comment by Franck-Dernoncourt** [comment]
I would be glad to assist you. Which step of https://github.com/Franck-Dernoncourt/NeuroNER/blob/master/install_windows.md is unclear to you?

**Comment by Rabia-Noureen** [comment]
Thanks for the quick response. I have reset my windows in order to get rid of the previous installation and started the installation again. For the first step "Python 3.5, TensorFlow, and several other Python packages" i have installed them by following the instructions in the link  but for the command

 pip install -U networkx matplotlib scikit-learn scipy pycorenlp
ALL OTHER PACKAGES INSTALLED SUCCESSFULLY BUT
spicy package installation failed with an error pasted below(Sorry for the long text)........... 
Kindly guide me how i can resolve this error first 

Building wheels for collected packages: scipy, pycorenlp
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command c:\users\zill-e-huma\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ZILL-E~1\\AppData\\Local\\Temp\\pip-build-e5d9p_8s\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\ZILL-E~1\AppData\Local\Temp\tmpoe7xon70pip-wheel- --python-tag cp35:
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\lib', 'C:\\', 'c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\libs']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\lib', 'C:\\', 'c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\libs']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels-jc1cl\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
    pre_dirs = system_info.get_paths(self, section, key)
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
    libraries lapack not found in ['c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\lib', 'C:\\', 'c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\libs']
    NOT AVAILABLE

  c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  non-existing path in 'scipy\\integrate': 'quadpack.h'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ZILL-E~1\AppData\Local\Temp\pip-build-e5d9p_8s\scipy\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\ZILL-E~1\AppData\Local\Temp\pip-build-e5d9p_8s\scipy\setup.py", line 412, in setup_package
      setup(**metadata)
    File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\ZILL-E~1\AppData\Local\Temp\pip-build-e5d9p_8s\scipy\setup.py", line 336, in configuration
      config.add_subpackage('scipy')
    File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command c:\users\zill-e-huma\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ZILL-E~1\\AppData\\Local\\Temp\\pip-build-e5d9p_8s\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).


  ----------------------------------------
  Failed cleaning build dir for scipy
  Running setup.py bdist_wheel for pycorenlp ... done
  Stored in directory: C:\Users\Zill-E-Huma\AppData\Local\pip\Cache\wheels\7d\a4\5f\c53f3d7ec0338384640719996d72ddb6d3a9a0f6b095b634f5
Successfully built pycorenlp
Failed to build scipy
Installing collected packages: decorator, networkx, cycler, pyparsing, pytz, python-dateutil, matplotlib, scikit-learn, scipy, idna, chardet, certifi, urllib3, requests, pycorenlp
  Running setup.py install for scipy ... error
    Complete output from command c:\users\zill-e-huma\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ZILL-E~1\\AppData\\Local\\Temp\\pip-build-e5d9p_8s\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ZILL-E~1\AppData\Local\Temp\pip-1ofstwft-record\install-record.txt --single-version-externally-managed --compile:

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\lib', 'C:\\', 'c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\lib', 'C:\\', 'c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels-jc1cl\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
      pre_dirs = system_info.get_paths(self, section, key)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\lib', 'C:\\', 'c:\\users\\zill-e-huma\\appdata\\local\\programs\\python\\python35\\libs']
      NOT AVAILABLE

    c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ZILL-E~1\AppData\Local\Temp\pip-build-e5d9p_8s\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\ZILL-E~1\AppData\Local\Temp\pip-build-e5d9p_8s\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\ZILL-E~1\AppData\Local\Temp\pip-build-e5d9p_8s\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\zill-e-huma\appdata\local\programs\python\python35\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "c:\users\zill-e-huma\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ZILL-E~1\\AppData\\Local\\Temp\\pip-build-e5d9p_8s\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ZILL-E~1\AppData\Local\Temp\pip-1ofstwft-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ZILL-E~1\AppData\Local\Temp\pip-build-e5d9p_8s\scipy\

**Comment by Rabia-Noureen** [comment]
I was also not able to install BRAT and TensorBoard during the previous installation because the link below when clicked was not working.
BRAT should now be accessible through the web browser at http://127.0.0.1:8001.

I would be thankful for your kind support.

**Comment by Franck-Dernoncourt** [comment]
To install scipy, assuming you use python 3.5, you can try:

1. Download `scipy‑0.19.0‑cp35‑cp35m‑win_amd64.whl` from http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy
2. Open `cmd`
3. Make sure `scipy‑0.19.0‑cp35‑cp35m‑win_amd64.whl` is in `cmd`'s current directory, then type `pip install scipy‑0.19.0‑cp35‑cp35m‑win_amd64.whl`.

Another solution is to use    [Anaconda](https://www.continuum.io/downloads), which is a python distribution  that comes with many packages  including scipy.


>I was also not able to install BRAT and TensorBoard during the previous installation because the link below when clicked was not working.

Before visiting  http://127.0.0.1:8001 did you try  installing BRAT?

**Comment by Rabia-Noureen** [comment]
Sorry for bothering you again and again but i am stuck with the installation again as i am new to python....
Thanks for the steps i have followed them and installed every thing except brat up till now while installing brat:
mkdir brat
cd brat
wget http://weaver.nlplab.org/~brat/releases/brat-v1.3_Crunchy_Frog.tar.gz
tar xzf brat-v1.3_Crunchy_Frog.tar.gz
cd brat-v1.3_Crunchy_Frog
./install.sh -u
All these worked fine for me but
executing python standalone.py gave the following error 

Zill-E-Huma@Haier-PC ~/brat/brat-v1.3_Crunchy_Frog
$ python standalone.py
  File "standalone.py", line 257
    except SystemExit, sts:
                     ^
SyntaxError: invalid syntax

May be its because my current directory should be changed to                                                
C:\Users\Zill-E-Huma\AppData\Local\Programs\Python\Python35 before running the script?or                C:\cygwin\home\Zill-E-Huma\brat\brat-v1.3_Crunchy_Frog is fine?
I cant find the problem kindly suggest some thing.

**Comment by Franck-Dernoncourt** [comment]
Could you please run `python -- version`? I suspect cygwin now comes with python 3, whereas BRAT needs 2.7.

**Comment by Rabia-Noureen** [comment]
Sir i have run that command and the version is 
$ python --version
Python 3.5.2
That is the version that i have installed following https://github.com/FranckDernoncourt/NeuroNER/blob/master/install_windows.md 
as TensorFlow currently supports only Python 3.5. So what should i do now is there any solution?

**Comment by Franck-Dernoncourt** [comment]
For BRAT, all the commands should be run  inside the cygwin terminal. As a side note, you don't have to use BRAT to be able to run NeuroNER. BRAT is only needed to easily create, change or view the annotations.

**Comment by Rabia-Noureen** [comment]
Thanks for your time and guidance the system is working perfectly fine now. I just wanted to ask that what should be  the max epoch_number value should be to train the model at the first run of main.py? I tried to change it by python main.py --maximum_number_of_epochs=2 --token_pretrained_embedding_filepath=""
And after 3 or 4 runs the model starts training again. Should it stop at some point?
One more thing is it necessary for the newly added data set to be in either CoNLL-2003 or BRAT format?Will a simple amazon review data set file be able to work fine? If not kindly share a method for conversion into the required format. And what if i have a single data set file that is not divided into 3 files training, validation and test set?Is it okay?

**Comment by Rabia-Noureen** [comment]
Also when i tried to run TensorBoard Graphs were not visible(May be i am using it wrong) in the Graphs tab i have attached the screen shots below
![1](https://user-images.githubusercontent.com/29410483/27256667-7a3d8104-53d6-11e7-9e1d-bf3e4573d66b.JPG)
![2](https://user-images.githubusercontent.com/29410483/27256668-7a45104a-53d6-11e7-81fa-9d02a8c4f6f4.JPG)

**Comment by Franck-Dernoncourt** [comment]
You're welcome :-) Could you please create a new issue for each question you asked in your previous two messages?

**Comment by Franck-Dernoncourt** [comment]
Thanks!
