### ISSUE TITLE
Labelling the same entity more than once? 

### ISSUE THREAD

**Issue by JohnGiorgi** [Franck-Dernoncourt/NeuroNER#27]
Is there anyway to train the model such that it will label the *same entity with multiple classes*? For example [here](http://compbio.ucdenver.edu/Craft/index.xhtml#/11532192), you can see some entities are labeled as both genes and proteins. 

If this is possible, how would I go about doing it? And if not, consider this a feature request! ;)

**Comment by Franck-Dernoncourt** [comment]
This isn't possible yet,  so I'll take it as a feature request :)

**Comment by JohnGiorgi** [comment]
Awesome:) Really appreciate that! You can follow the link to a loaded BRAT example in my above comment if that helps!

Cheers.
