### ISSUE TITLE
Using for production purpose

### ISSUE THREAD

**Issue by CMinhBui** [Franck-Dernoncourt/NeuroNER#31]
I'm trying to use my trained model as an API that input is text and the output is the labeled text. However, it's seem like every time i want to deploy ,it's need to initialize the model again. Can i separate the initialization and the predicting part so that I just have to load the model once then I can use it for predicting  several inputs at different times. 
Thank you for your amazing model :) 

I have read the thread #5 for this issue but i didn't quite get the solution for this problem.

**Comment by Franck-Dernoncourt** [comment]
There is no solution yet. However we are working on it :-)

**Comment by jennyjylee** [comment]
Sweetie, shouldn't we release our latest code??

**Comment by Franck-Dernoncourt** [comment]
Yes. I think so. I was waiting for you to have a more stable schedule in
case things breakdown and I also wanted to fist have the paper accepting.

**Comment by Franck-Dernoncourt** [comment]
Separating the initialization and the predicting part was done on the series of commits on Jul 11, 2017.
