### ISSUE TITLE
Unable to provide parameters to prepare_pretrained_model.py

### ISSUE THREAD

**Issue by JohnGiorgi** [Franck-Dernoncourt/NeuroNER#32]
Currently, it is not possible to provide the parameters to `prepare_pretrained_model.py` via a config file or command line arguments (unless I am mistaken!). Thus, the user has to modify the code in order to use this script to save their own pre-trained models. 

Should I add this feature and make a pull request?

**Comment by InternetMedical** [comment]
@JohnGiorgi 
Besides, there is a minor error in prepare_pretrained_model.py line 106 and 107.

original code:
     input_model_folder = os.path.join('.', 'output', output_folder_name, 'model')   # author might get it wrong
    output_model_folder = os.path.join('.', 'trained_models', model_name)

Actually, it might be changed as :
    # replace input_model_folder with output_model_folder
    output_model_folder = os.path.join('.', 'output', output_folder_name, 'model')   
    input_model_folder = os.path.join('.', 'trained_models', model_name)
