### ISSUE TITLE
FileNotFoundError with conll_output_filepath

### ISSUE THREAD

**Issue by davidbenton** [Franck-Dernoncourt/NeuroNER#34]
I'm trying to follow the [steps from the README](https://github.com/Franck-Dernoncourt/NeuroNER#using-neuroner) to run NeuroNER using the default parameters.ini settings. I'm running into a `FileNotFoundError` at [train.py, line 95](https://github.com/Franck-Dernoncourt/NeuroNER/blob/5d6105011caa9e049ecd3c88ca08e03e1564a55b/src/train.py#L95).

I'm new to python, but will try to track down the source of the issue. It looks like maybe the file should've been created by [this line](https://github.com/Franck-Dernoncourt/NeuroNER/blob/5d6105011caa9e049ecd3c88ca08e03e1564a55b/src/train.py#L93), but it's not clear to me why.

This is on ubuntu 16.04, python 3.5.2. Any advice on how to debug this issue?

Here's partial output from running `python main.py`:
```
Starting epoch 0
Training completed in 0.00 seconds
Evaluate model on the train set
Traceback (most recent call last):
  File "main.py", line 445, in <module>
    main()
  File "main.py", line 392, in main
    y_pred, y_true, output_filepaths = train.predict_labels(sess, model, transition_params_trained, parameters, dataset, epoch_number, stats_graph_folde$
, dataset_filepaths)
  File "/home/user/neuroner/neuroner/src/train.py", line 113, in predict_labels
    prediction_output = prediction_step(sess, dataset, dataset_type, model, transition_params_trained, stats_graph_folder, epoch_number, parameters, dat$
set_filepaths)
  File "/home/user/neuroner/neuroner/src/train.py", line 95, in prediction_step
    with open(conll_output_filepath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../output/en_2017-07-05_22-35-05-549137/000_train.txt_conll_evaluation.txt'

```

**Comment by Gregory-Howard** [comment]
Hi,
- Did you changed parameter.ini?
- Do you have /home/user/neuroner/neuroner/output ? 
- Do you have /home/user/neuroner/neuroner/output/en_2017-07-05_22-35-05-549137 ? 
- Write access problem?

**Comment by davidbenton** [comment]
Hi @Gregory-Howard! Sorry for the slow response. I didn't see a notification on your comment for some reason.

- **Did you changed parameter.ini?** No.
- **Do you have /home/user/neuroner/neuroner/output ?** Yes.
- **Do you have /home/user/neuroner/neuroner/output/en_2017-07-05_22-35-05-549137 ?** Yes.
- **Write access problem?** No, doesn't look like it. I can create files in that directory, and the directories (output and output/en_2017_[...]) were created when I ran main.py. Everything looks normal: owner of all files/dirs is user, permissions are 775/664.

**Comment by Franck-Dernoncourt** [comment]
What's the output of "perl -v" in your terminal? (Just checking if perl is
around)

**Comment by davidbenton** [comment]
Yep, here's version output:
```
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 58 registered patches, see perl -V for more detail)

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by davidbenton** [comment]
Not sure if this is helpful, but I just printed `shell_command` and it evaluates to:
```
perl ./conlleval < ../output/en_2017-07-08_01-22-56-515116/000_train.txt > ../output/en_2017-07-08_01-22-56-515116/000_train.txt_conll_evaluation.txt
```
Does that look right?

**Comment by davidbenton** [comment]
Hmm... manually running that command works (i.e. creates ../output/en_2017-07-08_01-22-56-515116/000_train.txt_conll_evaluation.txt). But running it via main.py doesn't (or it gets deleted).

FYI, this is in a virtualenvwrapper environment, but so was my manual running of `perl ./conlleval < ../output/en_2017-07-08_01-22-56-515116/000_train.txt > ../output/en_2017-07-08_01-22-56-515116/000_train.txt_conll_evaluation.txt`

**Comment by davidbenton** [comment]
This was a memory error. The perl script wasn't able to complete because of insufficient memory, but os.system hides the error output. I increased the swapfile size and all's well.

**Comment by Franck-Dernoncourt** [comment]
Interesting, thanks for the follow-up!

**Comment by nader2929** [comment]
I am also running into the same issue however I am running POP_OS! which uses btfrs, so increasing the swapfile size is a bit problematic. 

```data/text_from_warcs/dataset/deploy/clueweb12-0000tw-00-00005.txt
Formatting deploy set from BRAT to CONLL... Done.
Converting CONLL from BIO to BIOES format... Done.
Predict labels for the deploy set
Formatting 006_deploy set from CONLL to BRAT... Done.
Traceback (most recent call last):
  File "neuroner_starter_code.py", line 124, in <module>
    load_neuroner()    
  File "neuroner_starter_code.py", line 79, in load_neuroner
    nn.predict(fileTxt)
  File "/home/wdps/.local/lib/python3.7/site-packages/neuroner/neuromodel.py", line 813, in predict
    annotation_filepath, verbose=True)
  File "/home/wdps/.local/lib/python3.7/site-packages/neuroner/brat_to_conll.py", line 73, in get_entities_from_brat
    with codecs.open(text_filepath, 'r', 'UTF-8') as f:
  File "/usr/lib/python3.7/codecs.py", line 898, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './output/temp_2021-11-19_00-25-04-988634/brat/deploy/temp_00006.txt'
```

This is the stack trace, any guidance from anyone would be appreciated. Any more needed info let me know.

Thank you

**Comment by nader2929** [comment]
> I am also running into the same issue however I am running POP_OS! which uses btfrs, so increasing the swapfile size is a bit problematic.
> 
> ```
> Formatting deploy set from BRAT to CONLL... Done.
> Converting CONLL from BIO to BIOES format... Done.
> Predict labels for the deploy set
> Formatting 006_deploy set from CONLL to BRAT... Done.
> Traceback (most recent call last):
>   File "neuroner_starter_code.py", line 124, in <module>
>     load_neuroner()    
>   File "neuroner_starter_code.py", line 79, in load_neuroner
>     nn.predict(fileTxt)
>   File "/home/wdps/.local/lib/python3.7/site-packages/neuroner/neuromodel.py", line 813, in predict
>     annotation_filepath, verbose=True)
>   File "/home/wdps/.local/lib/python3.7/site-packages/neuroner/brat_to_conll.py", line 73, in get_entities_from_brat
>     with codecs.open(text_filepath, 'r', 'UTF-8') as f:
>   File "/usr/lib/python3.7/codecs.py", line 898, in open
>     file = builtins.open(filename, mode, buffering)
> FileNotFoundError: [Errno 2] No such file or directory: './output/temp_2021-11-19_00-25-04-988634/brat/deploy/temp_00006.txt'
> ```
> 
> This is the stack trace, any guidance from anyone would be appreciated. Any more needed info let me know.
> 
> Thank you

So realised that some of my text files are empty which also causes this error. 
Adding a check for that got rid of the error.
