### ISSUE TITLE
i2b2 data

### ISSUE THREAD

**Issue by peterwilliams97** [Franck-Dernoncourt/NeuroNER#35]
Not sure if this the right forum. The i2b2 most closely fits my intended usage of NeuroNER (identifying documents with private information, for a privacy application). 

I emailed schurchill@partners.org with a a signed data use agreement then followed up with another email in June this year. She has not replied.

Do you have any new advice on how to obtain the i2b2 data?

**Comment by Franck-Dernoncourt** [comment]
Sorry to hear, do you mind trying the fax? If no answer by the end of this
week please let me know and I'll ping someone else.

**Comment by Franck-Dernoncourt** [comment]
If still no reply, please send me your data use agreement at franck.dernoncourt@gmail.com and I'll see what I can do.
