### ISSUE TITLE
Loading token embedding from pretrained model for prediction

### ISSUE THREAD

**Issue by CMinhBui** [Franck-Dernoncourt/NeuroNER#38]
I'm not sure is this true or not but after inspecting the code and trying some different initial deploy set,
seem like in the deploy part, the loading token embedding step only load tokens that are in the dataset(deploy) when initialize, and ignore the other new tokens in the seperated prediction step. Therefore, if the initial deploy set is not large enough, it would not be able to load the full tokens embedding set in the pretrained model, as a result, the predict result will be pretty bad.
I think it would be better if the token embeded can be loaded completely with out depending on the initial data set. This can be solve by using the whole trainning data to init when deploying.
Sorry if I misunderstood the code.

**Comment by Franck-Dernoncourt** [comment]
You can to set `load_all_pretrained_token_embeddings` to True when loading the model, e.g.
`nn = NeuroNER(load_all_pretrained_token_embeddings=True)`, or as CLI argument, or in parameters.ini (https://github.com/Franck-Dernoncourt/NeuroNER/blob/0a8a98ab3678641dd8d5758c8c1c116f93ab3114/src/parameters.ini#L93-L94)
