### ISSUE TITLE
Using token embeddings in word2vec binary format 

### ISSUE THREAD

**Issue by JohnGiorgi** [Franck-Dernoncourt/NeuroNER#39]
@Franck-Dernoncourt 
Quick question,

I am just wondering if it is possible to use token embeddings provided in the **word2vec binary format**. In the readme, a link to token embeddings saved as a **plain text** are provided but there is no mention of whether NeuroNER supports token embeddings in other formats. 

Thanks very much in advance!

**Comment by Franck-Dernoncourt** [comment]
We currently don't support it, maybe we could add that in the future, in the meantime https://github.com/Franck-Dernoncourt/NeuroNER/issues/21 has some code for binary -> text conversion

**Comment by JohnGiorgi** [comment]
@Franck-Dernoncourt 
Thats very useful, I will try to use the code to convert to text. 

Thanks very much!
