### ISSUE TITLE
Using NeuroNER with Brat with custom annotations

### ISSUE THREAD

**Issue by robertkviby** [Franck-Dernoncourt/NeuroNER#49]
Hi Franck and all the rest of you!
First, thanks for all the great work with this.

I am trying to get started with using NeuroNER on a dataset I have annotated with BRAT, within a specific domain (music), so the entities are all custom. And, I want to add this dataset, to NeuroNER, by adding the BRAT-files (the txt-file and the ann-file), and then train on that. But I am not getting anywhere.

As I have understood it from your docs is that I should put both the train.txt and the train.ann in a folder and then point to that in parameters.ini, but I guess I misunderstood because I'm not making progress...

Could you offer some guidance on how to get started with this?

Best regards,
Robert

**Comment by JohnGiorgi** [comment]
@robertkviby 
Hi Robert, 
I have nothing to do with building NeuroNER but I know the answer to your question so I might as well help!

You need to divide your `.txt` and `.ann` files into folders named `test`, `valid`, and `train`. _I think_ `valid` is optional but I believe `test` and `train` are required. 

So for example, if in `parameters.ini` you set the `dataset_text_folder` to `../data/music`, then that directory would look like...

```
data/
    music/
        train/
            ex1.txt
            ann1.txt
            .
            .
        test/
            ex60.txt
            ann60.txt
            .
            .
        valid/
            ex90.txt
            ann90.txt
            .
            .
```
Notice that you point `dataset_text_folder` to the folder that _contains_ the `test`, `valid` and `train` folders and _not those folders themselves_. 

I am not sure how familiar with machine learning you are, but a typical split of your dataset would be 60/20/20 train/test/valid.

Hope this make sense,
Cheers!

**Comment by robertkviby** [comment]
@JohnGiorgi 
Hi, and thanks for your fast reply. I tried it now and I get an error (see stack below). I have created the folder structure your proposed above and in each of the folders are one .txt brat file and one .ann brat file with annotations.

`TensorFlow version: 1.2.1
{'character_embedding_dimension': 25,
 'character_lstm_hidden_state_dimension': 50,
 'dataset_text_folder': '../data/datadisko',
 'dropout_rate': 0.5,
 'experiment_name': 'Load more embeddings',
 'is_character_lstm_bidirect': 1,
 'is_token_lstm_bidirect': 1,
 'maximum_number_of_epochs': 100,
 'maximum_training_time': 10,
 'number_of_cpu_threads': 8,
 'number_of_gpus': 0,
 'optimizer': 'sgd',
 'patience': 10,
 'remove_unknown_tokens': 1,
 'tagging_format': 'bio',
 'token_embedding_dimension': 100,
 'token_lstm_hidden_state_dimension': 50,
 'token_pretrained_embedding_filepath': '../data/word_vectors/glove.6B.100d.txt',
 'train_model': 'true',
 'use_character_lstm': 1,
 'use_crf': 1}
Load embeddings
number_of_loaded_word_vectors: 400000
Load embeddings completed
Traceback (most recent call last):
  File "main.py", line 442, in <module>
    main()
  File "main.py", line 253, in main
    dataset.load_dataset(dataset_filepaths, parameters)
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/dataset.py", line 101, in load_dataset
    character_count[dataset_type] = self._parse_dataset(dataset_filepaths[dataset_type],dataset_type,all_pretrained_tokens,token_count)
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/dataset.py", line 25, in _parse_dataset
    f = codecs.open(dataset_filepath, 'r', 'UTF-8')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '../data/datadisko/train.txt'
<img width="661" alt="screenshot 2017-07-30 11 31 42" src="https://user-images.githubusercontent.com/24256490/28752236-b4721d7a-751a-11e7-8d52-3037c8d17262.png">
`

Does one need to "flag" somewhere that the BRAT format is used?

Best regards,
Robert

**Comment by robertkviby** [comment]
@JohnGiorgi and @Franck-Dernoncourt 

I think that my issues might have to do with that I downloaded the wrong version. In the screenshot below there is a link to one zip on neuroner.com and one zip on Github and it seems that they have different content. I first downloaded the one from neuroner.com (and ran into the issues above) and then I downloaded the zip from Github and that one acts a bit different... 

Could the neuroner.com be an old zip?

Best,
Robert
<img width="1019" alt="screenshot 2017-07-30 12 17 49" src="https://user-images.githubusercontent.com/24256490/28752518-24cbee46-7522-11e7-9b19-21e6b0feff13.png">

**Comment by robertkviby** [comment]
So now I get the following error instead:

`NeuroNER version: 1.0-dev
TensorFlow version: 1.2.1
{'character_embedding_dimension': 25,
 'character_lstm_hidden_state_dimension': 25,
 'check_for_digits_replaced_with_zeros': 1,
 'check_for_lowercase': 1,
 'dataset_text_folder': '../data/datadisko',
 'debug': 0,
 'dropout_rate': 0.5,
 'experiment_name': 'test',
 'freeze_token_embeddings': 0,
 'gradient_clipping_value': 5.0,
 'learning_rate': 0.005,
 'load_all_pretrained_token_embeddings': 0,
 'load_only_pretrained_token_embeddings': 0,
 'main_evaluation_mode': 'conll',
 'maximum_number_of_epochs': 1,
 'number_of_cpu_threads': 8,
 'number_of_gpus': 0,
 'optimizer': 'sgd',
 'output_folder': '../output',
 'parameters_filepath': './parameters.ini',
 'patience': 10,
 'plot_format': 'pdf',
 'pretrained_model_folder': '../trained_models/conll_2003_en',
 'reload_character_embeddings': 1,
 'reload_character_lstm': 1,
 'reload_crf': 1,
 'reload_feedforward': 1,
 'reload_token_embeddings': 1,
 'reload_token_lstm': 1,
 'remap_unknown_tokens_to_unk': 1,
 'spacylanguage': 'en',
 'tagging_format': 'bioes',
 'token_embedding_dimension': 100,
 'token_lstm_hidden_state_dimension': 100,
 'token_pretrained_embedding_filepath': '../data/word_vectors/glove.6B.100d.txt',
 'tokenizer': 'spacy',
 'train_model': 1,
 'use_character_lstm': 1,
 'use_crf': 1,
 'use_pretrained_model': 0,
 'verbose': 0}
Checking compatibility between CONLL and BRAT for train_spacy set ... Done.
Checking validity of CONLL BIOES format... Done.
Checking compatibility between CONLL and BRAT for valid_spacy set ... Done.
Converting CONLL from BIO to BIOES format... Done.

    Warning: no model found for 'en'

    Only loading the 'en' tokenizer.

Formatting test set from BRAT to CONLL... Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 245, in main
    nn = NeuroNER(**arguments)
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/neuroner.py", line 258, in __init__
    dataset_filepaths, dataset_brat_folders = self._get_valid_dataset_filepaths(parameters)
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/neuroner.py", line 171, in _get_valid_dataset_filepaths
    brat_to_conll.brat_to_conll(dataset_brat_folders[dataset_type], dataset_filepath_for_tokenizer, parameters['tokenizer'], parameters['spacylanguage'])
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/brat_to_conll.py", line 146, in brat_to_conll
    sentences = get_sentences_and_tokens_from_spacy(text, spacy_nlp)
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/brat_to_conll.py", line 20, in get_sentences_and_tokens_from_spacy
    for span in document.sents:
  File "spacy/tokens/doc.pyx", line 438, in __get__ (spacy/tokens/doc.cpp:9707)
ValueError: Sentence boundary detection requires the dependency parse, which requires data to be installed. For more info, see the documentation: 
https://spacy.io/docs/usage

Exception ignored in: <bound method NeuroNER.__del__ of <neuroner.NeuroNER object at 0x102309208>>
Traceback (most recent call last):
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/neuroner.py", line 489, in __del__
    self.sess.close()
AttributeError: 'NeuroNER' object has no attribute 'sess'`

**Comment by JohnGiorgi** [comment]
@robertkviby 

> Does one need to "flag" somewhere that the BRAT format is used?

To the best of my knowledge the answer is no, it appears that NeuroNER determines the dataset format while running.

> Could the neuroner.com be an old zip?

Seems likely that the `.zip` on the NeuroNER site and the code on GitHub will not be in perfect sync. Probably best to go with the `.zip` on GitHub if you want to ensure you have the latest features/improvements.

As per your last error message, are you sure you followed all the instructions for installing NeuroNER on mac (you can find them [here](https://github.com/Franck-Dernoncourt/NeuroNER/blob/master/install_mac.md)). Based on this error:

> ValueError: Sentence boundary detection requires the dependency parse, which requires data to be installed. For more info, see the documentation:
https://spacy.io/docs/usage

It seems like you might have forgot to run these two lines, as per the [Mac installation instructions](https://github.com/Franck-Dernoncourt/NeuroNER/blob/master/install_mac.md):

```
sudo pip3 install -U networkx matplotlib scikit-learn scipy spacy pycorenlp
python3.5 -m spacy download en
```
Make sure the packages install correctly and the spacy download completes. Then try running NeuroNER with your dataset again.

Cheers,
John.

**Comment by robertkviby** [comment]
Ah, I did execute those lines but when I did it again now I see an error that I missed the first time. That is probably the root cause.

`PermissionError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/en_core_web_sm/en_core_web_sm-1.2.0' -> '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spacy/data/en'
`

Thanks for your help @JohnGiorgi 
Robert

**Comment by JohnGiorgi** [comment]
@robertkviby 
No worries at all. 

Just remember to close the issue if this did indeed solve your problem!

Cheers,
John.

**Comment by robertkviby** [comment]
Well, actually, the error remains...

I have the model installed:
`    spaCy version      1.9.0          
    Python version     3.5.3          
    Platform           Darwin-16.1.0-x86_64-i386-64bit
    Location           /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spacy
    Installed models    en  `

But, the error is still:
`Load dataset... Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 245, in main
    nn = NeuroNER(**arguments)
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/neuroner.py", line 263, in __init__
    token_to_vector = dataset.load_dataset(dataset_filepaths, parameters)
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/dataset.py", line 333, in load_dataset
    token_indices, label_indices, character_indices_padded, character_indices, token_lengths, characters, label_vector_indices = self._convert_to_indices(dataset_filepaths.keys())
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/dataset.py", line 111, in _convert_to_indices
    label_binarizer.fit(range(max(index_to_label.keys()) + 1))
ValueError: max() arg is an empty sequence
Exception ignored in: <bound method NeuroNER.__del__ of <neuroner.NeuroNER object at 0x101b38208>>
Traceback (most recent call last):
  File "/Users/robertkviby/Dropbox/Datadisko/Neuroner/src/neuroner.py", line 489, in __del__
    self.sess.close()
AttributeError: 'NeuroNER' object has no attribute 'sess'`

**Comment by robertkviby** [comment]
Ok. The reason for the error above was that I had used a [Relation] in the Brat file. When I removed that, and only used [Entities], it worked.

Thanks for the input!

**Comment by Franck-Dernoncourt** [comment]
Thanks, good to know, I added the enhancement tag as NeuroNER should be able to ignore relations.

**Comment by thiptanawat** [comment]
@JohnGiorgi @Franck-Dernoncourt 
Hello, could you please help me to fix this issue? I'm working on Bio-NLP and my dataset is a bunch of *.ann and *.txt. I read and follow through the issue and got the same error as below.

`Formatting train set from BRAT to CONLL... Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 245, in main
    nn = NeuroNER(**arguments)
  File "/NeuroNER-master/src/neuroner.py", line259, in __init__
    dataset_filepaths, dataset_brat_folders = self._get_valid_dataset_filepaths(parameters)
  File "/NeuroNER-master/src/neuroner.py", line172, in _get_valid_dataset_filepaths
    brat_to_conll.brat_to_conll(dataset_brat_folders[dataset_type], dataset_filepath_for_tokenizer, parameters['tokenizer'], parameters['spacylanguage'])
  File "/NeuroNER-master/src/brat_to_conll.py",line 146, in brat_to_conll
    sentences = get_sentences_and_tokens_from_spacy(text, spacy_nlp)
  File "/NeuroNER-master/src/brat_to_conll.py",line 20, in get_sentences_and_tokens_from_spacy
    for span in document.sents:
  File "doc.pyx", line 521, in __get__
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or setsentence boundaries by setting doc[i].is_sent_start.
Exception ignored in: <bound method NeuroNER.__del__ of <neuroner.NeuroNER object at 0x7fc2f77c3438>>
Traceback (most recent call last):
  File "/NeuroNER-master/src/neuroner.py", line490, in __del__
    self.sess.close()
AttributeError: 'NeuroNER' object has no attribute 'sess'`

And after running python3 main.py again, I got this:

`Checking compatibility between CONLL and BRAT for train_spacy set ... Done.
Converting CONLL from BIO to BIOES format... Done.
Formatting valid set from BRAT to CONLL... Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 245, in main
    nn = NeuroNER(**arguments)
  File "/NeuroNER-master/src/neuroner.py", line259, in __init__
    dataset_filepaths, dataset_brat_folders = self._get_valid_dataset_filepaths(parameters)
  File "/NeuroNER-master/src/neuroner.py", line172, in _get_valid_dataset_filepaths
    brat_to_conll.brat_to_conll(dataset_brat_folders[dataset_type], dataset_filepath_for_tokenizer, parameters['tokenizer'], parameters['spacylanguage'])
  File "/NeuroNER-master/src/brat_to_conll.py",line 146, in brat_to_conll
    sentences = get_sentences_and_tokens_from_spacy(text, spacy_nlp)
  File "/NeuroNER-master/src/brat_to_conll.py",line 20, in get_sentences_and_tokens_from_spacy
    for span in document.sents:
  File "doc.pyx", line 521, in __get__
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or setsentence boundaries by setting doc[i].is_sent_start.
Exception ignored in: <bound method NeuroNER.__del__ of <neuroner.NeuroNER object at 0x7f9670c62400>>
Traceback (most recent call last):
  File "/NeuroNER-master/src/neuroner.py", line490, in __del__
    self.sess.close()
AttributeError: 'NeuroNER' object has no attribute 'sess'`

The third-time running is a different error:

`Checking compatibility between CONLL and BRAT for train_spacy set ... Done.
Checking validity of CONLL BIOES format... Done.
Checking compatibility between CONLL and BRAT for valid_spacy set ... Done.
Converting CONLL from BIO to BIOES format... Done.
Load dataset... Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 245, in main
    nn = NeuroNER(**arguments)
  File "/NeuroNER-master/src/neuroner.py", line264, in __init__
    token_to_vector = dataset.load_dataset(dataset_filepaths, parameters)
  File "/NeuroNER-master/src/dataset.py", line 333, in load_dataset
    token_indices, label_indices, character_indices_padded, character_indices, token_lengths, characters, label_vector_indices = self._convert_to_indices(dataset_filepaths.keys())
  File "/NeuroNER-master/src/dataset.py", line 111, in _convert_to_indices
    label_binarizer.fit(range(max(index_to_label.keys()) + 1))
ValueError: max() arg is an empty sequence
Exception ignored in: <bound method NeuroNER.__del__ of <neuroner.NeuroNER object at 0x7fa28c864438>>
Traceback (most recent call last):
  File "/NeuroNER-master/src/neuroner.py", line490, in __del__
    self.sess.close()
AttributeError: 'NeuroNER' object has no attribute 'sess'`

I already checked my dataset as @robertkviby has done by removing all [Relations] and [Events] except [Entities] but I still get this error. My dataset structure already includes train, valid, and test folders as @JohnGiorgi suggested:

> data/
    music/
        train/
            ex1.txt
            ex1.ann
            .
            .
        test/
            ex60.txt
            ex60.ann
            .
            .
        valid/
            ex90.txt
            ex90.ann
            .
            .

But right now I still can't fix this error. Please give me some advice about this.

Thanks
Mic

**Comment by JohnGiorgi** [comment]
@thiptanawat 

Hi and sorry for the super late response. So just looking at the error messages, I don't know whats going on. Also, you mention that you get different errors on different runs, what is changing between those runs to cause this?

I would start by making sure your Standoff format corpus is properly annotated (see [here](http://brat.nlplab.org/standoff.html)). Also, is this a well known dataset from BioNLP? If so let me know which one and I might be able to be more useful.

I noticed you are working on BioNLP. If you want, you can check out our tool [here](https://github.com/BaderLab/Saber). It is still a work in progress, and only takes CoNLL formatted datasets for now, but I will be putting a lot of hours into the tool for the foreseeable future so I can quickly implement new functionality / fix issues over there. 

(Sorry for a bit of a non-answer)
