### ISSUE TITLE
Why do you use final_states?

### ISSUE THREAD

**Issue by Yeom** [Franck-Dernoncourt/NeuroNER#6]
At entity_lstm.py
you get two returns from bidirectional_dynamic_rnn

1. outputs

2. final_states  = (c_states, h_states)

why do you use h_states? I don't know the difference between h_states of final states and last output in outputs

**Comment by Franck-Dernoncourt** [comment]
`h_states` of `final_states` should be the same as the last output in `outputs`.

From https://www.tensorflow.org/api_docs/python/tf/nn/bidirectional_dynamic_rnn ([mirror](https://web.archive.org/web/20170504180829/https://www.tensorflow.org/api_docs/python/tf/nn/bidirectional_dynamic_rnn)):

> output_states (which corresponds to final_states in the NeuroNER code): A tuple (output_state_fw, output_state_bw) containing the forward and the backward final states of bidirectional rnn.

**Comment by Yeom** [comment]
Thanks for solving my curious!

I'm really get helped!! :)
