### ISSUE TITLE
http://neuroner.com/ --> Forbidden

### ISSUE THREAD

**Issue by dansandland** [Franck-Dernoncourt/NeuroNER#63]
NeuroNER website is not accessible and so the word embeddings download fails: 
```
➜ wget http://neuroner.com/data/word_vectors/glove.6B.100d.zip
--2017-09-18 14:55:23--  http://neuroner.com/data/word_vectors/glove.6B.100d.zip
Resolving neuroner.com... 128.30.192.12
Connecting to neuroner.com|128.30.192.12|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-09-18 14:55:23 ERROR 403: Forbidden.
```
Is there an alternative link for the word embeddings?

**Comment by Franck-Dernoncourt** [comment]
Thanks for the report, I'll look into this 403. Alternative link for the word embeddings: http://nlp.stanford.edu/data/glove.6B.zip

**Comment by Franck-Dernoncourt** [comment]
Fixed. Crossing fingers the server don't have some issues again (i.e., that other people using the same server don't change things again), and I may move to another server at some point.
