### ISSUE TITLE
Theory behind network architecture

### ISSUE THREAD

**Issue by lminer** [Franck-Dernoncourt/NeuroNER#7]
I was wondering if you had an accompanying paper for this or if it was inspired by a paper. I'm trying to figure out the rational for architecture choice. For example, why the CRF layer?

**Comment by Franck-Dernoncourt** [comment]
We presented the architecture in: _De-identification of Patient Notes with Recurrent Neural Networks_. JAMIA 2016. https://doi.org/10.1093/jamia/ocw156 (without paywall: http://sci-hub.cc/10.1093/jamia/ocw156 or https://arxiv.org/pdf/1606.03475.pdf -> the arXiv version is slightly outdated).

Amongst other things, the paper presents an ablation analysis showing to what extent the CRF (a.k.a. seq opt -> sequence optimization) matters:

![image](https://cloud.githubusercontent.com/assets/15331/25718658/e181734a-30d4-11e7-9381-a46f88dd824c.png)
