### ISSUE TITLE
Add License to the codebase

### ISSUE THREAD

**Issue by chenzheruc** [Franck-Dernoncourt/NeuroNER#89]
Hello, could you please add a license to the codebase? like Apache license?

**Comment by JohnGiorgi** [comment]
Also mentioned in #46 and #15, no response yet from owner of the repository.

**Comment by tompollard** [comment]
Duplicate of https://github.com/Franck-Dernoncourt/NeuroNER/issues/46, https://github.com/Franck-Dernoncourt/NeuroNER/issues/15
