### ISSUE TITLE
Use NeuroNER for SRL

### ISSUE THREAD

**Issue by gcvineel** [Franck-Dernoncourt/NeuroNER#90]
First of all, thanks for making this code available Franck

my question: Are there any specific design constraints that make this code suitable only for NER (hence the name NeuroNER)? or could I use it for other tasks like Semantic Role Labeling? I am guessing the model will mimic the training data. In other words, if the training tags are interpreted as SRL then NeuroNER might very well be considered an SRL model too. 

Are you able to comment on should I expect poorer performance using this code for SRL?

**Comment by nkrot** [comment]
why don't you try?

**Comment by gcvineel** [comment]
That's an non-answer answer. I do plan to try it. But, before I do so I was checking with the author of the software on what his opinion on the matter was. But looks like the author is not active on this board anymore. Thanks anyway
