### ISSUE TITLE
Testing of model

### ISSUE THREAD

**Issue by Mrinal18** [Franck-Dernoncourt/NeuroNER#96]
How do we test this model in any test file?

**Comment by mcavdar** [comment]
Please run it:
https://github.com/Franck-Dernoncourt/NeuroNER/blob/9ad77899842d6bd3d4bd4f5c79c891b5d57faf12/README.md#L103-L107
Your annotated text will appear in **example_unannotated_texts_#datestamp** folder. (000_deploy.txt)
